// packages/typography-vue/src/components/Paragraph/index.vue
<template>
  <div
    :style="{ visibility: suffixWidth === null ? 'hidden' : 'initial' }"
    v-ellipsis
  >
    <span
      v-if="!!displayText && recognizeLineBreaks"
      v-html="displayText.replace(/\n/g, '<br />').replace(/\\n/g, '<br />')"
    ></span>
    <span v-else-if="!!displayText && !recognizeLineBreaks">
      {{displayText}}
    </span>

    <span
      v-if="!!suffix"
      v-suffix
      :style="{
        visibility: !displayText ? 'hidden' : 'initial',
        display: displayText === fullText ? 'none' : 'initial',
        color: '#7395f7',
        cursor: 'pointer',
        ...expandStyle,
      }"
      @click="onExpand"
    >
      <template v-if="!$slots.suffix">{{ suffix }}</template>
      <slot name="suffix"></slot>
    </span>

    <div
      v-if="packupable && displayTextBeforeExpand"
      :style="{
        display: displayText === displayTextBeforeExpand ? 'none' : 'block',
        color: '#7395f7',
        cursor: 'pointer',
        textAlign: 'right',
        ...packupStyle,
      }"
      @click="onPackup"
    >
      <template v-if="!$slots.packup">{{ packup }}</template>
      <slot name="packup"></slot>
    </div>
  </div>
</template>

<script lang="ts">
import formatWithEllipsis from "@typography-org/native";

export default {
  props: ["ellipsis"],
  data() {
    const text = this.$slots.default()[0].children;
    const {
      expandable,
      expandStyle,
      packupable,
      packupStyle,
      recognizeLineBreaks,
      rows,
      suffix: extraSuffix,
    } = this.ellipsis;

    const suffix = extraSuffix ? extraSuffix : expandable ? "展开" : null;

    return {
      expandable,
      expandStyle,
      packup: '收起',
      packupable,
      packupStyle,
      recognizeLineBreaks,
      rows,
      suffix,
      fullText: text?.trim(),
      displayText: null,
      displayTextBeforeExpand: null,
      suffixWidth: !!suffix ? null : 0,
    };
  },
  setup() {
    return {};
  },
  directives: {
    suffix: {
      mounted(dom, binding) {
        binding.instance.suffixWidth = dom.offsetWidth;
      },
    },
    ellipsis: {
      mounted(dom, binding, vm) {
        try {
          const vm = binding.instance;
          const ellipsis = vm.ellipsis;
          const { rows, recognizeLineBreaks } = ellipsis;
          const width = dom.offsetWidth;
          const fontSize = +getComputedStyle(dom).fontSize.replace("px", "");
          const fontFamily = +getComputedStyle(dom).fontFamily;
          const suffixWidth = vm.suffixWidth;
          const text = vm.$slots.default()[0].children?.trim();
          const calcFn = formatWithEllipsis.default || formatWithEllipsis;
          const newDisplayText = calcFn(
            text,
            {
              length: width * rows,
              lines: rows,
              fontSize,
              ellipsisWidth: suffixWidth,
              fontFamily,
            },
            {
              recognizeLineBreaks,
            }
          );
          vm.displayText = newDisplayText;
          vm.displayTextBeforeExpand = newDisplayText;
        } catch (err) {
          console.error(err);
        }
      },
    },
  },
  methods: {
    onExpand() {
      if (!this.expandable) return;
      this.displayText = this.fullText;
    },
    onPackup() {
      if (!this.packupable) return;
      this.displayText = this.displayTextBeforeExpand;
    },
  },
};
</script>

// packages/typography-react/src/components/Paragraph/index.tsx
import React, { useCallback, useEffect, useState } from 'react';
import formatWithEllipsis from '@typography-org/native';

export interface Ellipsis {
  /**
   * if recognize line breaks
   * @default false
   */
  recognizeLineBreaks?: boolean;
  /**
   * ellipsis more than how many lines
   */
  rows: number;
  /**
   * ellipsis occupy
   */
  suffix?: React.ReactNode | string;
  /**
   * enable expand
   * @default false
   */
  expandable?: boolean;
  /**
   * expand text style
   */
  expandStyle?: React.CSSProperties;
  /**
   * packup element or string
   */
  packup?: React.ReactElement | string;
  /**
   * enable packup
   * @default false
   */
  packupable?: boolean;
  /**
   * packup text style
   */
  packupStyle?: React.CSSProperties;
}

export interface Props {
  /** [ellipsisConfig](#api-ellipsisconfig) */
  ellipsis: Ellipsis;
  /**
   * when the omission is triggered, click the callback of the text box
   */
  onClickWhenEllipsis?: (event: React.MouseEvent) => void;
  /** will compute text */
  children: string;
}

const Paragraph: React.FC<Props> = props => {
  const { ellipsis = { } as Ellipsis } = props;
  const {
    expandable,
    expandStyle,
    packup: packupEl,
    packupable,
    packupStyle,
    recognizeLineBreaks = false,
    rows,
    suffix: extraSuffix
  } = ellipsis;

  const suffix = extraSuffix
    ? extraSuffix
    : expandable
      ? '展开'
      : null;

  const packup = packupEl || '收起';

  const [displayText, setDisplayText] = useState<string>(null);
  const [displayTextBeforeExpand, setDisplayTextBeforeExpand] = useState<string>(null);
  const [suffixWidth, setSuffixWidth] = useState<number>(!!suffix ? null : 0);
  const [containerInfo, setContainerInfo] = useState<any>(null);

  const suffixRefCb = useCallback((dom: HTMLSpanElement) => {
    if (!dom) return null;
    setSuffixWidth(dom.offsetWidth);
  }, []);

  const containerRefCb = useCallback((dom: HTMLDivElement) => {
    if (!dom) return null;
    setContainerInfo({
      width: dom.offsetWidth,
      fontSize: +getComputedStyle(dom).fontSize.replace('px', ''),
      fontFamily: getComputedStyle(dom).fontFamily,
    });
  }, [])

  useEffect(() => {
    if (suffixWidth === null) return;
    if (containerInfo === null) return;
    console.log('suffix width', suffixWidth);
    const { width, fontSize, fontFamily } = containerInfo;
    const newDisplayText = formatWithEllipsis(props.children, {
      length: width * rows,
      lines: rows,
      fontSize,
      ellipsisWidth: suffixWidth,
      fontFamily,
    }, {
      recognizeLineBreaks,
    });
    setDisplayText(newDisplayText);
    setDisplayTextBeforeExpand(newDisplayText);
  }, [suffixWidth, containerInfo])

  const onExpand = () => {
    if (!expandable) return;
    setDisplayText(props.children);
  }

  const onPackup = () => {
    if (!packupable) return;
    setDisplayText(displayTextBeforeExpand);
  }

  return (
    <div
      style={{ visibility: suffixWidth === null ? 'hidden' : 'initial' }}
      ref={containerRefCb}
      onClick={
        displayText !== props.children && !!props.onClickWhenEllipsis
          ? props.onClickWhenEllipsis
          : undefined
      }
    >
      {
        !!displayText &&
        (
          recognizeLineBreaks
            ? <span dangerouslySetInnerHTML={{ __html: displayText.replace(/\n/g, '<br />').replace(/\\n/g, '<br />') }} />
            : <span>{displayText}</span>
        )
      }

      {
        !!suffix &&
        <span
          ref={suffixRefCb}
          style={{
            visibility: !displayText ? 'hidden' : 'initial',
            display: displayText === props.children ? 'none' : 'initial',
            color: '#7395f7',
            cursor: 'pointer',
            ...expandStyle,
          }}
          onClick={onExpand}
        >
          {suffix}
        </span>
      }

      {
        packupable && displayTextBeforeExpand &&
        <div
          style={{
            display: displayText === displayTextBeforeExpand ? 'none' : 'block',
            color: '#7395f7',
            cursor: 'pointer',
            textAlign: 'right',
            ...packupStyle,
          }}
          onClick={onPackup}
        >
          {packup}
        </div>
      }
    </div>
  )
}

export default Paragraph;
